{
    "language": "nix",
    "before_install": [
        "sudo mkdir --parents /etc/nix",
        "echo 'substituters = https://cache.nixos.org https://cp6t.cachix.org' | sudo tee --append /etc/nix/nix.conf",
        "echo 'require-sigs = false'                                           | sudo tee --append /etc/nix/nix.conf",
        "echo 'sandbox = true'                                                 | sudo tee --append /etc/nix/nix.conf"
    ],
    "script": [
        "export CP6T_CACHIX=1",
        "./sanity.sh",
        "./maintenance.sh",
        "./nix-build.sh ./ecosystem",
        "result/bin/cp6t-ecosystem database generate ecosystem/database.sqlite3"
    ]
}
